---

 - name: Install Nginx Repository 
   apt_repository: repo='ppa:nginx/stable' state=present
   register: ppainstalled
 
 - name: Update Repositories 
   apt: update_cache=true
 
 - name: Install Nginx
   apt: pkg=nginx state=installed 
   when: ppainstalled|success
   register: nginxinstalled
   notify:
     - Restart Nginx
 
 - name: Write  modified nginx.conf
   when: nginxinstalled|success
   template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf backup=yes
   notify:
     - Restart Nginx

 - name: Start and Enable Nginx
   service: name=nginx state=started enabled=yes 

 - name: Disable Default Nginx Site
   file: dest=/etc/nginx/sites-enabled/default state=absent
   notify:
     - Restart Nginx

 - name: Add the "{{ app_name }}" config
   template: src=virtualhost.conf.j2 dest=/etc/nginx/sites-available/{{ app_name }} owner=root group=root
   notify:
     - Restart Nginx

 - name: Enable "{{ app_name }}" Site Config
   file: src=/etc/nginx/sites-available/{{ app_name }} dest=/etc/nginx/sites-enabled/{{ app_name }} state=link
   notify:
     - Restart Nginx
